### ISSUE TITLE
predict.py instructions are unclear.

### ISSUE THREAD

**Issue by khuang0312** [adriankucharski/WNet-UNet-SegNet-corneal#2]
In the readme, it says that I should make a folder called "test" in the "Training_data" folder, then put the images I want to predict inside that folder. It always keeps predicting though on the pictures in the "org" folder.

Changing the "to_predict" line in the config.ini didn't seem to work.

I think there might be an offending line also in the predict.py because I noticed a path is hardcoded to the org folder. Changing that seemed to have no effect.

**Comment by adriankucharski** [comment]
Unfortunatly, this is another out of date information in readme. 
Framework is designed to train and predict images with cross_validation setup. Default numbers of folds is 5 so we train on 80% images and predict on 20%.
For example, we have dataset that contains 5 images: [1.png, 2.png, 3.png, 4.png, 5.png], so we train a network 5 times:
Fold 1. To predict: [1.png], Training data: [2.png, 3.png, 4.png, 5.png]
Fold 2. To predict: [2.png], Training data: [1.png, 3.png, 4.png, 5.png]
Fold 3. To predict: [3.png], Training data: [1.png, 2.png, 4.png, 5.png]
Fold 4. To predict: [4.png], Training data: [1.png, 2.png, 3.png, 5.png]
Fold 5. To predict: [5.png], Training data: [1.png, 2.png, 3.png, 4.png]

**Comment by khuang0312** [comment]
Gotcha, thank you so much for the help. This really clarifies what's going on here.

**Comment by khuang0312** [comment]
Thank you honestly for providing some valuable information on your program as well as much needed context as this really isn't my strong suit. I apologize greatly for the inconveniences I have thrust upon you.

So assuming if I used your training method with the datasets you used, would it be possible to predict on entirely new pictures without corresponding field and ground truth images?

I assuming no...

For example, we have dataset that contains 5 images: [1.png, 2.png, 3.png, 4.png, new1.png], so we train a network 5 times:
Fold 1. To predict: [new1.png], Training data: [1.png, 2.png, 4.png, 3.png]
Fold 2. To predict: [1.png], Training data: [3.png, 1.png, new1.png, 2.png]
Fold 3. To predict: [2.png], Training data: [1.png, 2.png, 4.png, 3.png]
Fold 4. To predict: [3.png], Training data: [1.png, new1.png, 4.png, 2.png]
Fold 5. To predict: [4.png], Training data: [2.png, 1.png, 3.png, 4.png]

I assume not though, because you need to be able to train on new1.png at some point if you end up picking it for the training data for the current fold.

But if it is possible... do you just do the whole process again?

Config the config.ini file
Run prepare_dataset.py
Run training.py
Run predict.py

Or can you simply just run predict.py?

**Comment by adriankucharski** [comment]
Of course, it would be possible to predict entirely new pictures without any extra data. You can run predict.py as many times as you want to. But there are certain limitations, new pictures that you want to predict should be similar to images that were used to training the networks.

As I mentioned before, scripts are designed to predict on cross-validation setup, but I added a script that allows you to predict images from your own path. All you need is a trained network. To train network on whole dataset set 'folds_number' in config.ini to 1, run prepare_dataset.py, then training.py and finally what you get is trained networks that you can use with predict_from_path.py script.

**Comment by khuang0312** [comment]
Thanks for all your help! predict_from_path.py works excellently as you intended! 

I would recommend adding those instructions to the readme for others who follow your work.
