### ISSUE TITLE
How to prepare your own dataset for training / file directory in repo contradicts readme...

### ISSUE THREAD

**Issue by khuang0312** [adriankucharski/WNet-UNet-SegNet-corneal#3]
From what I gather...

You have five folders: field, gt, gt_all, markers, and org.

Do you have to manually create your own field images, ground truth images, ground truth all images, and marker images for any dataset you want to train upon? If so, how exactly does one do that? Is it possible to inform me about this process? 

What's the difference between gt and gt_all? I notice there's a dot. Are both folders required?

Also, your original readme says that you should have gt, hdf5, org, field. HDF5 doesn't seem to exist. So I imagine I just need field, gt, gt_all, markers, and org.

**Comment by adriankucharski** [comment]
Yes, you have to manually create your field and ground truth images. This is how neural networks work. We used Endothelial Cell Alizarine Data Set from http://bioimlab.dei.unipd.it/Endo%20Aliza%20Data%20Set.htm 

"gt_all" contains simple information about edges and cells, we do not use them for training, but we used them to generate images that are in "gt" directory. So our approach requires images from the "gt" folder. 

You do not need hdf5 folder, I forgot to remove it from readme.md. 

You can read more about the whole process in our paper https://authors.elsevier.com/c/1d9uA_djyJWB~o

**Comment by khuang0312** [comment]
So assuming if I used your training method with the datasets you used, would it be possible to predict on pictures without corresponding field and ground truth images?

**Comment by Corawill** [comment]
How do you make gt from gt_all? 
Does that method in these files? Is it public?
Thank you for your responese!

**Comment by adriankucharski** [comment]
Hi, @Corawill 
It's very simple algorithm and I'm not sure I added it to this repo, but all you need to do is:
1. Take an image from `gt_all`
2. Apply binary dilation (or erosion if edges have a value equal to 0)
3. Calculate centroid for every cells
4. Apply binary dilation/erosion to those centroids 
5. Add new image to an image from step 1.
